# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
